# -*- coding: utf-8 -*-
{
    "name": "Zipnova Odoo Connector",
    "summary": "Quote, create and track Zipnova shipments from Sales and eCommerce",
    "version": "17.0.3.0.0",
    "category": "Inventory/Delivery",
    "author": "OnlyOne",
    "website": "https://www.onlyone.com.ar",
    "license": "AGPL-3",
    "depends": [
        "sale",
        "delivery",
        "website",
        "website_sale",
        "mrp",
        "account",
        "stock",
        "sale_stock",
        "l10n_ar",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/zipnova_security.xml",
        "data/zipnova_data.xml",
        "views/delivery_views.xml",
        "views/res_company.xml",
        "views/res_config_settings_views.xml",
        "views/sale_views.xml",
        "views/sale_templates.xml",
        "views/res_partner.xml",
        "views/product.xml",
        "views/website_sale_delivery_templates.xml",
        "views/zipnova_pickup_views.xml",
        "wizard/choose_delivery_carrier_views.xml",
        "wizard/validate_delivery_carrier_wizard_views.xml",
        "views/account_move_view.xml",
        "views/stock_picking_view.xml",
        "reports/estimated_delivery_report.xml",
        "views/website_sale_templates.xml",
        "views/website_sale_view.xml",
        "views/sale_portal_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "zipnova/static/src/js/zipnova_odoo.js",
            "zipnova/static/src/scss/zipnova_odoo.scss",
        ],
    },
    "installable": True,
    "application": False,
}
